name             'jenkins-setup'
maintainer       'Soft Arch Team'
license          'all_rights'
description      'Custom jenkins setup for  soft arch team'
version '0.0.1'

depends 'ruby_tools', '~> 0.2.3'
depends 'java', '~> 0.1.6'
depends 'git', '~> 0.2.1'
depends 'users', '~> 0.1.1'
